### ISSUE TITLE
Small typo in one benchmark

### ISSUE THREAD

**Issue by Jayllyz** [yasuaki640/timingSafeEqual-bench#1]
11x faster, I was amazed :laughing: 

https://github.com/yasuaki640/timingSafeEqual-bench/blob/ab3f59b0edc28e1607bbea139490023e88cdb2f1/timingSafeEqual.bench.ts#L84

Should be `await timingSafeEqual2(a, b, (d: string) => sha256CryptoJS(d).toString());`

*Thanks for the fork, I've updated the CI to also run Bun if you want to update your repo.* ([bench.yaml](https://github.com/Jayllyz/parseHeader-bench/blob/main/.github/workflows/bench.yaml))

**Comment by yasuaki640** [comment]
@Jayllyz 
Thank you for pointing this out!
I will fork the repository again when needed.
